/**
 * Opens a print-ready academic report window so the user can save as PDF.
 */
export function exportReportPdf({ userName, report, courses, streak }) {
  const date = new Date().toLocaleDateString('en-GB', {
    weekday: 'long',
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });

  const { kpis, priorityTopics, courseRows, actions, recall, summary } = report;

  const priorityRows = priorityTopics
    .map(
      (t) =>
        `<tr><td>${t.name}</td><td>${t.courseCode}</td><td>${t.masteryLevel}%</td><td>${t.lastStudied ? new Date(t.lastStudied).toLocaleDateString('en-GB') : 'Never'}</td></tr>`,
    )
    .join('');

  const courseTable = courseRows
    .map(
      (c) =>
        `<tr><td>${c.code}</td><td>${c.name}</td><td>${c.avg}%</td><td>${c.below60} below 60%</td></tr>`,
    )
    .join('');

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Acad Learning Report</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: Georgia, serif; color: #111; padding: 48px; max-width: 720px; margin: 0 auto; }
    h1 { font-size: 28px; margin-bottom: 4px; }
    .meta { color: #555; font-size: 13px; margin-bottom: 32px; }
    h2 { font-size: 16px; margin: 28px 0 12px; border-bottom: 1px solid #ccc; padding-bottom: 6px; }
    .kpi-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin-bottom: 8px; }
    .kpi { border: 1px solid #ddd; padding: 12px; text-align: center; }
    .kpi-val { font-size: 22px; font-weight: bold; }
    .kpi-lbl { font-size: 10px; color: #666; text-transform: uppercase; margin-top: 4px; }
    ul { padding-left: 20px; line-height: 1.7; font-size: 14px; }
    li { margin-bottom: 8px; }
    table { width: 100%; border-collapse: collapse; font-size: 13px; margin-bottom: 8px; }
    th, td { border: 1px solid #ddd; padding: 8px 10px; text-align: left; }
    th { background: #f5f5f5; }
    .action { padding: 10px 0; border-bottom: 1px solid #eee; font-size: 14px; line-height: 1.5; }
    .summary { font-size: 15px; line-height: 1.65; margin-bottom: 24px; padding: 16px; background: #f9f9f9; border-left: 3px solid #14b8a6; }
    @media print { body { padding: 24px; } }
  </style>
</head>
<body>
  <h1>Acad Learning Report</h1>
  <p class="meta">${userName || 'Member'} · ${date} · ${streak?.current ?? 0}-day streak · Performance since you started</p>

  <h2>AI summary</h2>
  <p class="summary">${summary || 'No summary available yet.'}</p>

  <h2>Snapshot</h2>
  <div class="kpi-grid">
    <div class="kpi"><div class="kpi-val">${kpis.dueCards}</div><div class="kpi-lbl">Cards due</div></div>
    <div class="kpi"><div class="kpi-val">${kpis.weakTopics}</div><div class="kpi-lbl">Topics below 60%</div></div>
    <div class="kpi"><div class="kpi-val">${kpis.avgMastery}%</div><div class="kpi-lbl">Avg mastery</div></div>
    <div class="kpi"><div class="kpi-val">${typeof kpis.totalStudyHours === 'number' ? kpis.totalStudyHours.toFixed(1) : kpis.totalStudyHours}h</div><div class="kpi-lbl">Total study logged</div></div>
  </div>

  <h2>Recommended next steps</h2>
  ${actions.map((a) => `<div class="action"><strong>${a.priority}</strong> — ${a.text}</div>`).join('')}

  ${
    priorityRows
      ? `<h2>Priority topics</h2><table><thead><tr><th>Topic</th><th>Course</th><th>Mastery</th><th>Last studied</th></tr></thead><tbody>${priorityRows}</tbody></table>`
      : ''
  }

  <h2>Recall pipeline</h2>
  <p>Due: ${recall.due} · Learning: ${recall.learning} · Reviewing: ${recall.reviewing} · Mastered: ${recall.mastered}</p>

  ${
    courseTable
      ? `<h2>By course</h2><table><thead><tr><th>Code</th><th>Course</th><th>Mastery</th><th>Gaps</th></tr></thead><tbody>${courseTable}</tbody></table>`
      : ''
  }

  <p class="footer">Generated by Acad · Local device data only</p>
</body>
</html>`;

  const win = window.open('', '_blank');
  if (!win) return false;
  win.document.write(html);
  win.document.close();
  win.focus();
  setTimeout(() => win.print(), 400);
  return true;
}
